apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devoncloud.fullname" . }}
  labels:
    {{- include "devoncloud.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMapData | nindent 2 }}
